<center> <img src ="https://i.postimg.cc/1X8H7YYt/BITS-Logo.png" width = "400" alt="BITS Pilani Logo" /> </center>

<font color='green'> <h1> <center> Basics of NumPy Arrays - 2 </center> </h1> </font>


In [ ]:
import numpy as np

<b> Array Indexing<b>

Similar to list indexing, arrays can be accessed using the indices.

In [ ]:
nparray = np.array([1, 2, 3, 4, 5])

In [ ]:
#Access first element, indexing starts from 0
nparray[0]

np.int64(1)

In [ ]:
#Access second element, indexing starts from 0
nparray[1]

np.int64(2)

In [ ]:
#Access last element, negative indices works
nparray[-1]

np.int64(5)

In [ ]:
nparray[-2]

np.int64(4)

In multi-dimensional arrays, comma separated tupe of indices can be used to access elements.

In [ ]:
x = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Access element at location (0, 0), zeroth row and zeroth column
x[0,0]

np.int64(1)

In [ ]:
#Access element at location (1, 2), first row and second column
x[1,2]

np.int64(6)

Values can be modified using indices,

In [ ]:
#Modify the (0, 0)th entry to 555
x[0, 0] = 555
x

array([[555,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

<b> Array Slicing<b>

[] can be used access the sub arrays i.e. array sicing is supported similar to list. To access a slice of array x , use : <br>
x[start:stop:step]

In [ ]:
nparray

array([1, 2, 3, 4, 5])

In [ ]:
nparray[1:]  # all values after index 1

array([2, 3, 4, 5])

In [ ]:
nparray[ : 3] # all values till index 3

array([1, 2, 3])

In [ ]:
nparray[2:4] # all value between index 2 and 4

array([3, 4])

In [ ]:
nparray[::2]  #every other element

array([1, 3, 5])

In [ ]:
nparray[1::2]  #every other element starting from element at index 1

array([2, 4])

In [ ]:
nparray[::-1] # all elements in reversed direction

array([5, 4, 3, 2, 1])

In [ ]:
x

array([[555,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
x[ : 2, : 3] # first two rows, first three columns

array([[555,   2,   3],
       [  4,   5,   6]])

In [ ]:
#Accessing array rows
x[0, :]  # zeroth row , all columns

array([555,   2,   3])

In [ ]:
#Accessing array columns
x[:, 1]  # all row , second columns

array([2, 5, 8])

<b> Array copying<b>

Array slices are views, hence if they are modified then original array is changed.

In [ ]:
nparray

array([1, 2, 3, 4, 5])

In [ ]:
nparray_sub = nparray[2:4]   #Slice the array
nparray_sub

array([3, 4])

In [ ]:
nparray_sub[0] = 5  # modify the element of slice
nparray_sub

array([5, 4])

In [ ]:
nparray #original array is changed

array([1, 2, 5, 4, 5])

In order to prevent this behaviour copy needs to be done.

In [ ]:
nparray_copy = nparray[2:4].copy()  #create copy of array slice

In [ ]:
nparray_copy[0] = 90  # modify the slice
nparray_copy

array([90,  4])

In [ ]:
nparray  #original array is still intact

array([1, 2, 5, 4, 5])

<b> Reshaping of Arrays <b>

Reshape can be used to change the structure of array. Size of original and reshaped arrays should be same.

In [1]:
import numpy as np

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
array = np.array(a)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
array.reshape(5, 3)

ValueError: cannot reshape array of size 9 into shape (5,3)

Reshaping can be used to convert an array into row matrix or column matrix.

In [ ]:
x

array([[555,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
x.reshape(9, 1)

array([[555],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9]])

In [ ]:
x.reshape(1, 9)

array([[555,   2,   3,   4,   5,   6,   7,   8,   9]])

<b> Array Concatenation<b>

Joining of two arrays is possible through np.concatenate, np.vstack and np.hstack.

In [4]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
z = np.array([99, 99, 99])

In [5]:
np.concatenate([x, y, z])

array([ 1,  2,  3, 10, 20, 30, 99, 99, 99])

In [6]:
np.concatenate([x, y, z]).shape

(9,)

In [ ]:
two_d_array = np.array([[1, 2, 3], [4, 5,6]])
two_d_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([two_d_array, two_d_array])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.vstack([two_d_array, y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [ ]:
v_array = np.array([[99], [99]])

In [ ]:
np.hstack([two_d_array, v_array])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

<b> Array Splitting<b>

Splititng is done by split, vsplit and hsplit.

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
n1, n2, n3, n4 = np.split(x, [2, 5, 8 ])   # splitting position 2, 5, and 8

In [ ]:
print(n1, n2, n3, n4)

[1 2] [3 4 5] [6 7 8] [ 9 10]


In [ ]:
grid = np.random.rand(5, 3)
grid

array([[0.99777047, 0.96968403, 0.15594115],
       [0.37377096, 0.95102654, 0.53586551],
       [0.7943086 , 0.66602218, 0.50615888],
       [0.87377074, 0.27762393, 0.42222027],
       [0.98695333, 0.75449498, 0.69022787]])

In [ ]:
n1, n2 = np.split(grid, [3])  #splitting postion third row

In [ ]:
print(n1, "\n\n", n2)

[[0.99777047 0.96968403 0.15594115]
 [0.37377096 0.95102654 0.53586551]
 [0.7943086  0.66602218 0.50615888]] 

 [[0.87377074 0.27762393 0.42222027]
 [0.98695333 0.75449498 0.69022787]]


In [ ]:
n1, n2 = np.vsplit(grid, [1])

In [ ]:
print(n1, "\n\n", n2)

[[0.99777047 0.96968403 0.15594115]] 

 [[0.37377096 0.95102654 0.53586551]
 [0.7943086  0.66602218 0.50615888]
 [0.87377074 0.27762393 0.42222027]
 [0.98695333 0.75449498 0.69022787]]


In [ ]:
n1, n2 = np.hsplit(grid, [1])

In [ ]:
print(n1, "\n\n", n2)

[[0.99777047]
 [0.37377096]
 [0.7943086 ]
 [0.87377074]
 [0.98695333]] 

 [[0.96968403 0.15594115]
 [0.95102654 0.53586551]
 [0.66602218 0.50615888]
 [0.27762393 0.42222027]
 [0.75449498 0.69022787]]


<b> Fancy Indexing<b>

Here arrays of indices is passed to access the elements.

In [ ]:
nparray

array([1, 2, 5, 4, 5])

In [ ]:
indices = [1, 3, 4]  #indices first, third and fourth
nparray[indices] #elements at first , third and forth elements are returned

array([2, 4, 5])

In [ ]:
#Create a 2-d array using the indices
indices = np.array([[0,1], [3,4]])
nparray[indices]

array([[1, 2],
       [4, 5]])

In [ ]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
row = np.array([0, 1])
column = np.array([0,1])
row

array([0, 1])