<center> <img src ="https://i.postimg.cc/1X8H7YYt/BITS-Logo.png" width = "400" alt="BITS Pilani Logo" /> </center>

<font color='green'> <h1> <center> Aggregations with NumPy Arrays </center> </h1> </font>

NumPy provides provides various options for calculating summary statistics like min, max, sum, average, standard deviation, median etc.

<b> Sum operations comparison<b>

Lets compare built-in sum() with np.sum() for a big array.

In [1]:
import numpy as np

In [9]:
nparray = np.random.random(100)  # create np array of 100 random values
print("type : ", type(nparray))
sum(nparray)  # apply sum on it

type :  <class 'numpy.ndarray'>


np.float64(43.83154041857055)

In [10]:
np.sum(nparray)  # apply np.sum() on array

np.float64(43.83154041857055)

In [11]:
%timeit sum(nparray)

3.32 μs ± 68.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
%timeit np.sum(nparray)

6.45 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


np.sum() performs much better than the built-in sum() function.

<b> Finding mimimum and maximum<b>

In [12]:
nparray

array([0.06942117, 0.20667401, 0.45000157, 0.983149  , 0.98195403,
       0.93178499, 0.96122154, 0.28590116, 0.48488133, 0.22891996,
       0.3914205 , 0.5458812 , 0.12851442, 0.71237497, 0.18593407,
       0.05243114, 0.19253426, 0.2410432 , 0.93780571, 0.67430112,
       0.11158211, 0.62311155, 0.4578734 , 0.93651582, 0.15986595,
       0.14498131, 0.55033654, 0.37051436, 0.41441063, 0.07484672,
       0.21264599, 0.12015573, 0.27960449, 0.05813082, 0.10378571,
       0.26178781, 0.40543174, 0.33380777, 0.4187712 , 0.90703885,
       0.88632634, 0.47790883, 0.43168488, 0.47433589, 0.64489543,
       0.65578498, 0.18973455, 0.37138837, 0.14573647, 0.14389355,
       0.94786295, 0.05062983, 0.58124681, 0.93345392, 0.59418945,
       0.43163812, 0.1239508 , 0.21266598, 0.28287706, 0.45519602,
       0.25486215, 0.67046659, 0.5336943 , 0.05207669, 0.74456884,
       0.23305823, 0.67880267, 0.1859967 , 0.11325507, 0.48691734,
       0.47481824, 0.72371137, 0.00626042, 0.10901023, 0.86777

In [13]:
np.min(nparray)

np.float64(0.006260423773384649)

In [14]:
np.max(nparray)

np.float64(0.9857992200080636)

Other way to compute min and max using the array variable is as follows

In [15]:
nparray.min()

np.float64(0.006260423773384649)

In [16]:
nparray.max()

np.float64(0.9857992200080636)

<b> Multidimensional aggregates<b>

Computing aggregates over the complete array 

In [17]:
matrix = np.random.random((4, 4))
matrix

array([[0.48141927, 0.48980679, 0.66822647, 0.75257366],
       [0.96027362, 0.71514548, 0.66661277, 0.33258525],
       [0.56328799, 0.09432225, 0.32072315, 0.24113542],
       [0.27279802, 0.05202119, 0.06751428, 0.30366429]])

In [18]:
matrix.sum()

np.float64(6.982109899734819)

In [19]:
np.sum(matrix)

np.float64(6.982109899734819)

In [20]:
matrix.min()

np.float64(0.052021185612978416)

In [21]:
np.min(matrix)

np.float64(0.052021185612978416)

In [22]:
matrix.max()

np.float64(0.9602736238310375)

In [23]:
np.max(matrix)

np.float64(0.9602736238310375)

Computing agggregates within each Column

In [24]:
matrix

array([[0.48141927, 0.48980679, 0.66822647, 0.75257366],
       [0.96027362, 0.71514548, 0.66661277, 0.33258525],
       [0.56328799, 0.09432225, 0.32072315, 0.24113542],
       [0.27279802, 0.05202119, 0.06751428, 0.30366429]])

In [25]:
matrix.sum(axis=0)

array([2.27777891, 1.35129571, 1.72307667, 1.62995861])

In [26]:
np.sum(matrix, axis=0)

array([2.27777891, 1.35129571, 1.72307667, 1.62995861])

In [27]:
matrix.max(axis=0)

array([0.96027362, 0.71514548, 0.66822647, 0.75257366])

In [28]:
np.max(matrix, axis=0)

array([0.96027362, 0.71514548, 0.66822647, 0.75257366])

In [29]:
matrix.min(axis=0)

array([0.27279802, 0.05202119, 0.06751428, 0.24113542])

In [30]:
np.min(matrix, axis=0)

array([0.27279802, 0.05202119, 0.06751428, 0.24113542])

Computing agggregates within each Row

In [31]:
matrix

array([[0.48141927, 0.48980679, 0.66822647, 0.75257366],
       [0.96027362, 0.71514548, 0.66661277, 0.33258525],
       [0.56328799, 0.09432225, 0.32072315, 0.24113542],
       [0.27279802, 0.05202119, 0.06751428, 0.30366429]])

In [32]:
matrix.sum(axis=1)

array([2.39202619, 2.67461712, 1.21946881, 0.69599778])

In [33]:
np.sum(matrix, axis=1)

array([2.39202619, 2.67461712, 1.21946881, 0.69599778])

In [34]:
matrix.min(axis=1)

array([0.48141927, 0.33258525, 0.09432225, 0.05202119])

In [35]:
np.min(matrix, axis=1)

array([0.48141927, 0.33258525, 0.09432225, 0.05202119])

In [36]:
matrix.max(axis=1)

array([0.75257366, 0.96027362, 0.56328799, 0.30366429])

In [37]:
np.max(matrix, axis=1)

array([0.75257366, 0.96027362, 0.56328799, 0.30366429])

<b> Other aggregate functions<b>

In [38]:
matrix

array([[0.48141927, 0.48980679, 0.66822647, 0.75257366],
       [0.96027362, 0.71514548, 0.66661277, 0.33258525],
       [0.56328799, 0.09432225, 0.32072315, 0.24113542],
       [0.27279802, 0.05202119, 0.06751428, 0.30366429]])

In [39]:
matrix.prod()  # compute product of all values

np.float64(2.1584091531643812e-08)

In [40]:
matrix.mean()  # compute average of all values

np.float64(0.4363818687334262)

In [41]:
matrix.std()  # standard deviation

np.float64(0.2606891841195016)

In [42]:
matrix.var()  # variance

np.float64(0.0679588507168914)

<b> NaN -safe aggregate functions <b>

In [43]:
x = np.array([1, 5, 3, 4, 5])
x

array([1, 5, 3, 4, 5])

In [44]:
np.nansum(x)  # NaN safe sum , ignore missing values

np.int64(18)

In [45]:
np.nanmax(x)  # NaN safe max , ignore missing values

np.int64(5)

In [46]:
np.nanmin(x)  # NaN safe min , ignore missing values

np.int64(1)

In [47]:
np.nanstd(x)  # NaN safe std , ignore missing values

np.float64(1.4966629547095764)